language: csharp

services:
  - mysql
  - postgresql

script:
  - xbuild /p:Configuration=ReleaseMono linq2db.Mono.sln
  - preparetravis.sh
  - nunit-console Tests/Linq/bin/ReleaseMono/linq2db.Tests.dll

before_install:
  - sudo apt-get install nunit-console

before_script:
  - nuget restore linq2db.Mono.sln

