language: csharp

install:
  - nuget install NUnit.Runners -Version 3.5.0 -OutputDirectory testrunner

services:
  - mysql
  - postgresql

script:
  - xbuild /p:Configuration=ReleaseMono linq2db.Mono.sln
  - mv Tests/Linq/TravisDataProviders.txt Tests/Linq/UserDataProviders.txt
  - mysql -e 'CREATE DATABASE TestData;'
  - psql -c 'create database TestData;' -U postgres
  - nunit3-console 
  - mono ./testrunner/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe Tests/Linq/bin/ReleaseMono/linq2db.Tests.dll --where cat != WindowsOnly

#before_install:
#  - sudo apt-get install nunit3-console

before_script:
  - nuget restore linq2db.Mono.sln

