language: csharp
sudo: required
dist: trusty

mono:  
  - 4.2.3
os:  
  - linux
  - osx
osx_image: xcode7.1

before_install:  
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fiopenssl; fi

install:
  - nuget install NUnit.Runners -Version 3.5.0 -OutputDirectory testrunner

services:
  - mysql
  - postgresql

script:
  - mysql -e 'CREATE DATABASE TestData;'
  - psql -c 'create database testdata;' -U postgres
  - mv Tests/Linq/TravisDataProviders.txt Tests/Linq/UserDataProviders.txt
  - mv Tests/Linq/TravisDataProviders.Core.txt Tests/Linq/UserDataProviders.Core.txt
  - ./build.sh
#  - xbuild /p:Configuration=ReleaseMono linq2db.Mono.sln
#  - mono ./testrunner/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe Tests/Linq/bin/ReleaseMono/linq2db.Tests.dll --where "cat != WindowsOnly"

#before_install:
#  - sudo apt-get install nunit3-console

before_script:
  - nuget restore linq2db.Mono.sln

