image:
- Visual Studio 2017

configuration: Release

environment:
  packageVersion: 1.9.0
  access_token:
    secure: IlfmHXRdUK6v8dX/WqieXQ==
  matrix:
    - buildConfiguration: net45
    - buildConfiguration: netcoreapp1.1
    - buildConfiguration: docfx


version: $(packageVersion).{build}

cache:
- packages -> **\packages.config

services:
- mssql2012sp1
- mysql
- postgresql

init:
- cmd: git config --global core.autocrlf true
- ps: $env:buildVersion = "$env:packageVersion.$env:appveyor_build_number"
- ps: |
    if ($env:APPVEYOR_REPO_BRANCH -eq "release") 
    {
        $env:nugetVersion = "$env:packageVersion"
    }
    else
    {
        $env:nugetVersion = "$env:packageVersion-rc$env:appveyor_build_number"
    }
- ps: Update-AppveyorBuild -Version $env:buildVersion
- ps: .\AvInitDatabases.ps1
- cmd: 7z e Data\northwind.sql.zip
- cmd: sqlcmd -U sa -P Password12! -S localhost\SQL2012SP1 -i "northwind.sql" > nul

nuget:
  account_feed: false
  project_feed: false

build_script:
- ps: .\build.ps1

artifacts:
- path: \**\linq2db*.nupkg

deploy:
- provider: NuGet
  server: https://www.myget.org/F/linq2db/api/v2
  api_key:
    secure: LDw0jeA1Yo3R4/TKv2kmlgJR8dTT6Wun2MONq3uDvtVQJG4LOU9LjvVTAc7IgRfm
  skip_symbols: true
  on:
    branch: master

- provider: NuGet
  api_key:
    secure: oTYw2IwTnz4qMD8c/MR/6mo+Nx3wa5Pp8MYfsKBCKCVuU6QCHlj+6QMXpnQses8G
  on:
    branch: release

- provider: NuGet
  server: https://www.myget.org/F/linq2db/api/v2
  api_key:
    secure: LDw0jeA1Yo3R4/TKv2kmlgJR8dTT6Wun2MONq3uDvtVQJG4LOU9LjvVTAc7IgRfm
  skip_symbols: true
  on:
    branch: rc_version2

skip_commits:
  message: /ci skip/      # Regex for matching commit message